### ISSUE TITLE
reference for installation path wrong

### ISSUE THREAD

**Issue by Ehaxe** [msraredon/NICHES#1]
Path for installation is incorrect

To install NICHES in R, you may run:

library(devtools)
install_github('msraredon/Connectome', ref = 'master')

should be refering to NICHES as path
To install NICHES in R, you may run:

library(devtools)
install_github('msraredon/NICHES', ref = 'master')

**Comment by msraredon** [comment]
Fixed. Thank you for noticing this.

S
