### ISSUE TITLE
question about result meaning?

### ISSUE THREAD

**Issue by jinyuanchun** [msraredon/NICHES#10]
thank you for your great packages. i use it in my project.
i want to know the meaning of result?
![image](https://user-images.githubusercontent.com/40689145/204684466-a642ffbe-c312-4fb9-9691-18bee09cfa6b.png)

**Comment by msraredon** [comment]
I'm not entirely sure that I recognize correctly what you are posting, but if this is a screenshot of the NICHES CellToCell output matrix, transposed for python workflows, and your question is about the meaning of the numeric values:

These values are the product of ligand module expression on the sending cell with receptor module expression on the receiving cell. It is a proxy for 'connective intensity'. Scaling these values by mechanism (here, by column) will yield values reflecting z-scores within the dataset.

Statistical tests can be run on either the starting values or on scaled values to determine significance for a given question. We recommend following/modifying single-cell vignette workflows for these types of tasks, like that explained here: https://satijalab.org/seurat/articles/de_vignette.html

Does this help? Does this answer your question?

S
