### ISSUE TITLE
CellToSystem and SystemToCell metadata handling is not compatible with Seurat v5

### ISSUE THREAD

**Issue by RaredonLab** [msraredon/NICHES#27]
CellToSystem and SystemToCell metadata handling is not compatible with Seurat v5

The following error occurs:
![image](https://github.com/msraredon/NICHES/assets/138699095/5d077d34-7a34-4105-9c6d-5aa6ee9b988d)

**Comment by jcyang34** [comment]
This was addressed in commit f2c7004aa1abf43759a07e0d35c18693d99457dc and 633ed0b4a5b5c12a7cca3cb302ff598f40d8a4ab
