### ISSUE TITLE
Error: No cell overlap between new meta data and Seurat object

### ISSUE THREAD

**Issue by suerle** [msraredon/NICHES#34]
Hi, 

Thanks for this great tool.

NICHES has worked well for me in the past. However, now I am running into "Error: No cell overlap between new meta data and Seurat object".

I am trying to find ligand receptor networks upregulated in Visium spots with a certain annotation in meta.data column "hotspots".

Here is my code:
s12_niche@meta.data$x <- s12_niche@images$caudal_6.5_r_V13Y22.328_D1@coordinates$row
s12_niche@meta.data$y <- s12_niche@images$caudal_6.5_r_V13Y22.328_D1@coordinates$col
DefaultAssay(s12_niche) <- "Spatial"
s12_niche <- SeuratWrappers::RunALRA(s12_niche) 
s12_niche_output <- RunNICHES(object = s12_niche,
                           LR.database = "fantom5",
                           species = "human",
                           assay = "alra",
                           position.x = 'x',
                           position.y = 'y',
                           k = 4, 
                           cell_types = "hotspots",
                           min.cells.per.ident = 0,
                           min.cells.per.gene = NULL,
                           meta.data.to.map = c('orig.ident', 'hotspots'),
                           CellToCell = F,CellToSystem = F,SystemToCell = F,
                           CellToCellSpatial = F,CellToNeighborhood = F,NeighborhoodToCell = T).

Output:

Set cell types as Identity of object internally

 Subsetting to populations with greater than 0 cells

 3987 distinct cells from 2 celltypes to be analyzed

 Limiting ground truth to genes within dataset

 Mapping against 2470 ground truth signaling mechanisms
Compute edgelist based on mutual nearest neighbors.
Error: No cell overlap between new meta data and Seurat object

I would appreciate any help regarding potential issues.
Thank you!

**Comment by jcyang34** [comment]
this error should be fixed by the most recent version on master branch, feel free to reopen the issue if it still happens
