### ISSUE TITLE
getSeuratAssay function gives an error

### ISSUE THREAD

**Issue by madhavmantri** [msraredon/NICHES#36]
Hi, 

I am using the latest version of the NICHES and I found that the getSeuratAssay function called from RunNICHES method gives me this error:
```
Error in .make_numeric_version(x, strict, .standard_regexps()$valid_numeric_version) : 
  invalid non-character version specification 'x' (type: double)
```

The function uses this code to retrieve assay data depending on the Seurat Version:
```
getSeuratAssay <- function(object,assay,slot){
  if(SeuratObject::Version(object) >= 5) return(Seurat::GetAssayData(object,assay=assay,layer=slot))
  else return(Seurat::GetAssayData(object,assay=assay,slot=slot))
}
```
I think the cause of the error is SeuratObject's version function returns a character "4.0.0" which is being compared to 5.0 and it spits out the error pasted above. Can you please fix this?

Thank you. 
Madhav

**Comment by sdawood1** [comment]
I am having the same issue

**Comment by sdawood1** [comment]
Did you manage to fix the error youself?

**Comment by madhavmantri** [comment]
Yes. You can download the zip file for the package from github.

Then in the source code files in the R subfolder, I made the following edits:
1. In utils.R, change SeuratObject::Version(object) >= 5 to SeuratObject::Version(object) >= "5.0.0"
2. In RunCellToCellSpatial.R, RunCellToCell.R, RunCellToSystem.R, RunCellToNieghborhood.R, RunSystemToCell.R, RunNeighborhoodToCell.R, change SeuratObject::Version(demo) >= 5 to SeuratObject::Version(demo) >= "5.0.0"

After making all these edits, install the package from source using devtools::install_local("path_to_package_folder"), restart your R session, and you should be good to go.

**Comment by sdawood1** [comment]
> Yes. You can download the zip file for the package from github.
> 
> Then in the source code files in the R subfolder, I made the following edits:
> 
> 1. In utils.R, change SeuratObject::Version(object) >= 5 to SeuratObject::Version(object) >= "5.0.0"
> 2. In RunCellToCellSpatial.R, RunCellToCell.R, RunCellToSystem.R, RunCellToNieghborhood.R, RunSystemToCell.R, RunNeighborhoodToCell.R, change SeuratObject::Version(demo) >= 5 to SeuratObject::Version(demo) >= "5.0.0"
> 
> After making all these edits, install the package from source using devtools::install_local("path_to_package_folder"), restart your R session, and you should be good to go.

I am now getting the error after all this:

Error in RunCellToCell(sys.small = sys.small, ground.truth = ground.truth,  : 
  no slot of name "layers" for this object of class "Assay"

**Comment by sdawood1** [comment]
Nevermind,  I had to download the new release, thank you for your help!
